stages:
  - init
  - plan
  - apply

variables:
  TF_ROOT: infrastructure
  TF_IN_AUTOMATION: true
  AWS_REGION: eu-central-1

before_script:
  - apt-get update && apt-get install -y unzip
  - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
  - unzip terraform_1.0.11_linux_amd64.zip
  - mv terraform /usr/local/bin/
init:
  stage: init
  script:
    - find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u | while read -r dir; do
        echo "Initializing Terraform in $dir";
        cd $dir;
        terraform init;
        cd -;
      done
  only:
    - main
  artifacts:
    paths:
      - $TF_ROOT/**/.terraform
      - $TF_ROOT/**/.terraform.lock.hcl
    expire_in: 1 hour

plan:
  stage: plan
  script:
    - find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u | while read -r dir; do
        echo "Planning Terraform in $dir";
        cd $dir;
        terraform plan;
        cd -;
      done
  only:
    - main
  dependencies:
    - init

apply:
  stage: apply
  script:
    - find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u | while read -r dir; do
        echo "Applying Terraform in $dir";
        cd $dir;
        terraform apply -auto-approve;
        cd -;
      done
  only:
    - main
  when: manual
  dependencies:
    - init

