stages:
  - init
  - plan
  - apply

variables:
  TF_ROOT: infrastructure
  TF_IN_AUTOMATION: true
  AWS_REGION: eu-central-1

cache:
  key: terraform-cache
  paths:
    - $TF_ROOT/**/.terraform
    - $TF_ROOT/**/.terraform.lock.hcl

init:
  stage: init
  script:
    - find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u | while read -r dir; do
        echo "Initializing Terraform in $dir";
        cd $dir;
        terraform init -reconfigure;
        cd -;
      done
  only:
    - main

plan:
  stage: plan
  script:
    - find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u | while read -r dir; do
        echo "Planning Terraform in $dir";
        cd $dir;
        terraform plan;
        cd -;
      done
  only:
    - main

apply:
  stage: apply
  script:
    - find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u | while read -r dir; do
        echo "Applying Terraform in $dir";
        cd $dir;
        terraform apply -auto-approve;
        cd -;
      done
  only:
    - main
  when: manual