stages:
  - init
  - plan
  - apply

variables:
  TF_ROOT: infrastructure
  TF_IN_AUTOMATION: true
  AWS_REGION: eu-central-1

image:
  name: hashicorp/terraform:1.0.11
  entrypoint: [""]  # Disable the default Terraform entrypoint

cache:
  key:
    files:
      - $TF_ROOT/**/.terraform.lock.hcl
    prefix: tf-$CI_PROJECT_ID
  paths:
    - $TF_ROOT/**/.terraform
  policy: pull-push

init:
  stage: init
  script:
    - |
      find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u | while read -r dir; do
        echo "Initializing Terraform in $dir"
        cd "$dir"
        terraform init -reconfigure
        cd -
      done
  only:
    - main

plan:
  stage: plan
  parallel:
    matrix:
      - TF_DIR: $(find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u)
  script:
    - |
      cd "${TF_DIR}"
      terraform init -reconfigure
      terraform plan -no-color -out=tfplan
  artifacts:
    paths:
      - ${TF_DIR}/tfplan
  only:
    - merge_requests
    - main

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - |
      cd "${TF_DIR}"
      terraform apply -auto-approve tfplan
  when: manual
  only:
    - main