stages:
  - init
  - plan
  - apply

variables:
  TF_ROOT: infrastructure
  TF_IN_AUTOMATION: true
  AWS_REGION: eu-central-1

image: hashicorp/terraform:1.0.11

cache:
  key:
    files:
      - $TF_ROOT/**/.terraform.lock.hcl
    prefix: tf-$CI_PROJECT_ID
  paths:
    - $TF_ROOT/**/.terraform
  policy: pull-push

init:
  stage: init
  script:
    - find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u | while read -r dir; do
        echo "Initializing Terraform in $dir";
        cd $dir;
        terraform init -reconfigure;
        cd -;
      done
  only:
    - main

plan:
  stage: plan
  script:
    - |
      for dir in $(find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u); do
        echo "Planning Terraform in $dir";
        cd $dir;
        terraform init -reconfigure;
        terraform plan -no-color -out=tfplan;
        cd -;
      done
  artifacts:
    paths:
      - $TF_ROOT/**/tfplan
  only:
    - merge_requests
    - main

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - |
      for dir in $(find $TF_ROOT -type f -name '*.tf' -exec dirname {} \; | sort -u); do
        echo "Applying Terraform in $dir";
        cd $dir;
        terraform apply -auto-approve tfplan;
        cd -;
      done
  when: manual
  only:
    - main
