FROM intervals-icu-puller-base:latest

WORKDIR /app

# Install test deps first
COPY tests/requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

# Copy application as a package
COPY app/ ./app
COPY tests/ ./tests

# Set the PYTHONPATH environment variable
ENV PYTHONPATH="/app"

ENTRYPOINT ["pytest", "tests/unit/", "-v"]