name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_VERSION: '1.8.5' # Use a more recent version of Terraform
  AWS_REGION: 'eu-central-1'

jobs:
  terraform:
    name: 'Terraform Plan/Apply'
    runs-on: ubuntu-latest
    # Use a matrix to define all your Terraform root directories
    strategy:
      matrix:
        tf_dir:
          - 'infrastructure/api_gateway/chart_data_api'
          - 'infrastructure/cloudwatch/step_functions'
          - 'infrastructure/ecr/lambda'
          - 'infrastructure/iam/lambda'
          - 'infrastructure/lambda/chart_data_api'
          - 'infrastructure/lambda/garmin_puller'
          - 'infrastructure/lambda/intervals_icu_puller'
          # NOTE: Do NOT include module directories here

    defaults:
      run:
        working-directory: ${{ matrix.tf_dir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use latest version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 # Use latest version
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false # To avoid deprecation warnings

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # Use latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.tf_dir }} # Unique artifact name per directory
          path: ${{ matrix.tf_dir }}/tfplan

      - name: Terraform Apply (Main Branch Only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false -auto-approve tfplan